steps:
  - name: node:12.21-slim
    id: npm-install
    entrypoint: 'npm'
    args:
      - ci
    dir: frontend
    waitFor:
      - '-'

  # Angular unit test
  - name: asia-northeast1-docker.pkg.dev/$PROJECT_ID/frontend/ng-test-runner
    id: angular-test
    entrypoint: 'npm'
    args:
      - run
      - test
    dir: frontend
    waitFor:
      - npm-install

  # Angular + nestjs build
  - name: node:12.21-slim
    id: angular-with-nest-build
    entrypoint: 'npm'
    args:
      - run
      - build:ssr
    dir: frontend
    waitFor:
      - npm-install

  # build Docker image with cache
  - name: 'gcr.io/kaniko-project/executor:v1.3.0'
    id: kaniko
    args:
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/jpsite/$BRANCH_NAME:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=6h
    waitFor:
      - angular-test
      - angular-with-nest-build

  # deploy Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:319.0.0'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - jpsite
      - --region=asia-northeast1
      - --platform=managed
      - --service-account=jpsite-run@$PROJECT_ID.iam.gserviceaccount.com
      - --max-instances=1
      - --cpu=1
      - --memory=256M
      - --concurrency=8
      - --image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/jpsite/$BRANCH_NAME:$COMMIT_SHA
    waitFor:
      - kaniko
