steps:
  - name: gcr.io/cloud-builders/docker
    args: ['run', '-d', '--network=cloudbuild', '--name=cds-emulator', 'google/cloud-sdk:248.0.0', 'gcloud', 'beta', 'emulators', 'datastore', 'start', '--host-port=0.0.0.0:8081']
  - name: jwilder/dockerize:0.6.1
    args: ['dockerize', '-timeout=60s', '-wait=tcp://cds-emulator:8081']
  - name: google/cloud-sdk:248.0.0
    env:
      - DATASTORE_EMULATOR_HOST=cds-emulator:8081
    args: ['sh', '-c', 'curl $${DATASTORE_EMULATOR_HOST}/v1/projects/example-project/indexes']
  - name: 'golang:1.11.5-stretch'
    entrypoint: 'go'
    args: ['test', '-v', './...']
    env:
      - 'GO111MODULE=on'
      - 'DATASTORE_EMULATOR_HOST=cds-emulator:8081'
  # for cloud-build-local
  - name: gcr.io/cloud-builders/docker
    args: ['rm', '--force', 'cds-emulator']

