steps:
  - name: gcr.io/cloud-builders/docker
    id: cds-emulator
    args: ['run', '-d', '--network=cloudbuild', '--name=cds-emulator', 'google/cloud-sdk:248.0.0', 'gcloud', 'beta', 'emulators', 'datastore', 'start', '--host-port=0.0.0.0:8081']
  - name: jwilder/dockerize:0.6.1
    args: ['dockerize', '-timeout=60s', '-wait=tcp://cds-emulator:8081']
  - name: 'golang:1.13-stretch'
    id: go-test
    entrypoint: 'go'
    args: ['test', '-v', './...']
    env:
      - 'GO111MODULE=on'
      - 'DATASTORE_EMULATOR_HOST=cds-emulator:8081'
      - 'GOOGLE_CLOUD_PROJECT=unittest'
    waitFor: ['cds-emulator']
  # angular build
  - name: node:12.13
    id: npm-ci
    entrypoint: 'npm'
    args: ['ci']
    dir: 'ng-app'
    waitFor: ['-']
  - name: node:12.13
    id: npm-run
    entrypoint: 'npm'
    args: ['run', 'prod']
    dir: 'ng-app'
    waitFor: ['npm-ci']
  # deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
    waitFor:
      - 'go-test'
      - 'npm-run'
  # for cloud-build-local
  - name: gcr.io/cloud-builders/docker
    args: ['rm', '--force', 'cds-emulator']